version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
      prefix-separator: ":"
    labels:
      - "dependencies"
      - "ci"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      python-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "build"
      prefix-separator: ":"
    labels:
      - "dependencies"
      - "build"
    ignore:
      - dependency-name: "godot*"
